version: '3.5'
services:

  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    volumes:
      - api_data:/docker_api
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=twtrubiks.com.tw
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=twtrubiks.com.tw
      - LETSENCRYPT_EMAIL=xxxx@gmail.com

  api:
    container_name: api-container
    build: ./api
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/docker_api
    networks:
      - proxy
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    networks:
      - proxy
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  api_data:
  pgdata:

networks:
  proxy:
    external:
      name: self-nginx-proxy