version: '3.5'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      # - vhost:/etc/nginx/vhost.d
      - ./vhost.d:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./custom_nginx.tmpl:/app/nginx.tmpl
      - ./nginx_log:/var/log/nginx

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - "nginx-proxy"
    volumes:
      - certs:/etc/nginx/certs
      # - vhost:/etc/nginx/vhost.d
      - ./vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - NGINX_PROXY_CONTAINER=nginx-proxy
      # - DEFAULT_EMAIL=xxx@xxx.xxx

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=foo.com,whoami.A.local,whoami.B.local,whoami.C.local


volumes:
  certs:
  html:
  # vhost:
  dhparam:


